# Generated by Django 3.1 on 2020-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music_band_package_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.CharField(max_length=100)),
                ('No_of_songs', models.CharField(max_length=10)),
                ('Charging_rate', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=200)),
                ('Other_Details', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'music_band',
            },
        ),
    ]
