# Generated by Django 3.1 on 2020-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('ContactEmail', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=200)),
                ('Fee', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'videography',
            },
        ),
        migrations.CreateModel(
            name='video_add2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'child',
            },
        ),
    ]
