# Generated by Django 3.1.1 on 2020-09-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video_add2',
        ),
    ]
