# Generated by Django 3.0.8 on 2020-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0002_delete_video_add2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_add',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
