# Generated by Django 3.0.8 on 2020-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0003_auto_20200909_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_add',
            name='Description',
            field=models.CharField(max_length=1200),
        ),
    ]
