# Generated by Django 3.0.8 on 2020-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0004_auto_20200909_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_add',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
