# Generated by Django 3.0.8 on 2020-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0005_auto_20201006_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='resources',
            fields=[
                ('Resources_ID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=40)),
                ('Admin_ID', models.CharField(max_length=40)),
                ('Facility_ID', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
