# Generated by Django 3.0.8 on 2020-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0006_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='samples/')),
            ],
            options={
                'db_table': 'video_samples',
            },
        ),
    ]
