# Generated by Django 3.0.8 on 2020-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0007_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_add',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='samples/'),
        ),
    ]
