# Generated by Django 3.0.8 on 2020-10-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0008_video_add_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_add',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='samples'),
        ),
    ]
