# Generated by Django 3.0.8 on 2020-10-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0009_auto_20201015_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samples',
            old_name='video',
            new_name='samples',
        ),
    ]
