# Generated by Django 3.0.8 on 2020-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0010_auto_20201016_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='samples',
            field=models.FileField(blank=True, null=True, upload_to='samples'),
        ),
    ]
