# Generated by Django 3.0.8 on 2020-10-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0011_auto_20201016_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='samples',
        ),
    ]
