# Generated by Django 3.0.8 on 2020-10-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0012_delete_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('Resources_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Samples', models.FileField(blank=True, null=True, upload_to='samples')),
            ],
            options={
                'db_table': 'video_samples',
            },
        ),
    ]
