# Generated by Django 3.0.8 on 2020-10-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0013_samples'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='samples',
            new_name='video_samples',
        ),
    ]
