# Generated by Django 3.0.8 on 2020-10-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0014_auto_20201016_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video_samples',
        ),
    ]
