# Generated by Django 3.0.8 on 2020-10-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videography', '0016_video_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_add',
            name='Status',
            field=models.CharField(default='In', max_length=10),
            preserve_default=False,
        ),
    ]
