# Generated by Django 3.0.8 on 2020-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('exp', models.CharField(max_length=80)),
                ('des', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('FB', models.CharField(max_length=80)),
                ('fee', models.CharField(max_length=80)),
            ],
        ),
    ]
