# Generated by Django 3.0.8 on 2020-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('exp', models.CharField(max_length=80)),
                ('des', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('FB', models.CharField(max_length=80)),
                ('fee', models.CharField(max_length=80)),
                ('profile_image', models.CharField(max_length=80)),
                ('sample_image1', models.CharField(max_length=80)),
                ('sample_image2', models.CharField(max_length=80)),
                ('sample_image3', models.CharField(max_length=80)),
                ('sample_image4', models.CharField(max_length=80)),
            ],
        ),
    ]
