# Generated by Django 3.0.8 on 2020-09-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
