# Generated by Django 3.0.8 on 2020-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sound_admin_upload',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Package_name', models.CharField(max_length=100)),
                ('Suitable_for', models.CharField(max_length=10)),
                ('Brand', models.CharField(max_length=45)),
                ('Price', models.CharField(max_length=45)),
                ('Description', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'soundsystem',
            },
        ),
    ]
