# Generated by Django 3.1.1 on 2020-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundsystems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sound_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Package_name', models.CharField(max_length=500)),
                ('Suitable_for', models.CharField(max_length=500)),
                ('Brand', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'soundsystem',
            },
        ),
        migrations.DeleteModel(
            name='sound_admin_upload',
        ),
    ]
