# Generated by Django 3.0.8 on 2020-09-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('Event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_type', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
