# Generated by Django 3.0.8 on 2020-10-18 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admin_login',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=40)),
                ('L_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='eventbin',
            fields=[
                ('Event_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Event_type', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=10)),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=100)),
                ('OnCreateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'completed_events',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('Event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_type', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=10)),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=100)),
                ('OnCreateTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('Reservation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_ID', models.CharField(max_length=10)),
                ('S_Time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('E_Time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Resources_ID', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
