# Generated by Django 3.0.8 on 2020-09-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('Reservation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Event_ID', models.CharField(max_length=10)),
                ('Time', models.CharField(max_length=20)),
                ('Resources_ID', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
