# Generated by Django 3.0.8 on 2020-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Date',
            field=models.CharField(default=2000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='Date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
