# Generated by Django 3.0.8 on 2020-10-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20201007_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventbin',
            new_name='bin',
        ),
    ]
