# Generated by Django 3.0.8 on 2020-10-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20201007_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bin',
        ),
    ]
