# Generated by Django 3.0.8 on 2020-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_delete_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventbin',
            fields=[
                ('Event_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Event_type', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Customer_ID', models.CharField(max_length=10)),
                ('Date', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'completed_events',
            },
        ),
    ]
