# Generated by Django 3.0.8 on 2020-10-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_eventbin'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=40)),
                ('L_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
