# Generated by Django 3.0.8 on 2020-10-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='Status',
        ),
    ]
