# Generated by Django 3.0.8 on 2020-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_reservations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Date',
            field=models.DateField(),
        ),
    ]
