# Generated by Django 3.0.8 on 2020-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20201008_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
