# Generated by Django 3.0.8 on 2020-10-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20201008_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
