# Generated by Django 3.0.8 on 2020-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20201009_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='Date',
            new_name='E_Time',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='Time',
        ),
        migrations.AddField(
            model_name='reservations',
            name='S_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
