# Generated by Django 3.0.8 on 2020-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20201009_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admin_login',
            },
        ),
    ]
