# Generated by Django 3.0.8 on 2020-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='admin_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
