# Generated by Django 3.0.8 on 2020-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_auto_20201010_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='E_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='S_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
