# Generated by Django 3.0.8 on 2020-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_auto_20201016_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='E_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='S_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
