# Generated by Django 3.0.8 on 2020-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20201016_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='OnCreateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
