# Generated by Django 3.0.8 on 2020-10-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_auto_20201016_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='OnCreateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
