# Generated by Django 3.0.8 on 2020-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20201016_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
