# Generated by Django 3.0.8 on 2020-10-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_auto_20201017_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbin',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
